In [1]:
import pandas as pd


In [5]:
data = [10,20,0.5,40]
series = pd.Series(data)
print(series)

0    10.0
1    20.0
2     0.5
3    40.0
dtype: float64


In [9]:
data = [1, 2, 3, 4, 5]
i = ['A','B','C','D','E']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
E    5
dtype: int64


In [11]:
data = {"A": 10, "B": 14, "C": 19, "D": 18}
series = pd.Series(data)
print(series)


A    10
B    14
C    19
D    18
dtype: int64


In [12]:
series.replace(18,14)

A    10
B    14
C    19
D    14
dtype: int64

In [17]:
series.drop("A")

B    14
C    19
D    18
dtype: int64

In [18]:
import numpy as np


In [21]:
data = np.array([100,200,300])
series = pd.Series(data, index = (['a', 'b' ,'c']))
print(series)

a    100
b    200
c    300
dtype: int32


In [27]:
data = {'Name':['Alice', 'John' , 'Bob'], 'Age': [23,45,65],
        'Country':['USA', 'UK', 'INDIA']}
df = pd.DataFrame(data)
print(df)


    Name  Age Country
0  Alice   23     USA
1   John   45      UK
2    Bob   65   INDIA


In [4]:
import numpy as np
import pandas as pd

In [6]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
df = pd.DataFrame(array)
print(df)
                                

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
